all: management communication

management: management.c
	gcc -o management management.c -lpthread

communication: communication.c
	gcc -o communication communication.c -lpthread

clean:
	rm -f management communication
